# Generated by Django 4.1.1 on 2022-11-20 10:58

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('control_number', models.CharField(max_length=10)),
                ('file_uuid', models.UUIDField(default=uuid.uuid4)),
                ('state', models.CharField(choices=[('', 'Empty'), ('ambigous', 'Ambiguous'), ('review', 'Review'), ('graded ', 'Graded')], default='emtpy', max_length=10)),
                ('correct_answers', models.IntegerField(default=0)),
                ('wrong_answers', models.IntegerField(default=0)),
                ('is_graded', models.BooleanField(default=False)),
                ('grade', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='ExamGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('num_questions', models.IntegerField()),
                ('avg_group_grade', models.FloatField(default=0.0)),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('chosen', models.CharField(choices=[('a', 'A'), ('b', 'B'), ('c', 'C'), ('d', 'D'), ('e', 'E'), ('', 'Empty')], default='', max_length=1)),
                ('correct', models.BooleanField(default=False)),
                ('threshold', models.FloatField(default=0.0)),
                ('a_filled', models.BooleanField(default=False)),
                ('b_filled', models.BooleanField(default=False)),
                ('c_filled', models.BooleanField(default=False)),
                ('d_filled', models.BooleanField(default=False)),
                ('e_filled', models.BooleanField(default=False)),
                ('graded_exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='opengrader_backend.exam')),
            ],
        ),
        migrations.CreateModel(
            name='KeySheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key_class', models.CharField(choices=[('a', 'A'), ('b', 'B'), ('c', 'C'), ('d', 'D'), ('e', 'E'), ('', 'Empty')], default='', max_length=1)),
                ('exam_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='opengrader_backend.examgroup')),
            ],
        ),
        migrations.CreateModel(
            name='KeyQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('chosen', models.CharField(choices=[('a', 'A'), ('b', 'B'), ('c', 'C'), ('d', 'D'), ('e', 'E'), ('', 'Empty')], default='', max_length=1)),
                ('key_sheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='key_questions', to='opengrader_backend.keysheet')),
            ],
        ),
        migrations.AddField(
            model_name='exam',
            name='exam_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='opengrader_backend.examgroup'),
        ),
        migrations.AddField(
            model_name='exam',
            name='key_sheet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='opengrader_backend.keysheet'),
        ),
    ]
